language: node_js
node_js:
- '12'
cache:
  yarn: true
deploy:
  provider: npm
  email: axyzxp@gmail.com
  api_key:
    secure: BFhPhXAqHHqSa95VRvX/vfq4WGynUNhHxAnBeyr8fQp8avGOSVXv5+ATd4V8tnThIbp/yBv+AoBMyj8Y8hqwyFlZ8a7ga7CJiJvQEKov2LBkPnnXq7S5LW7AoItWPqiAYM1/ZmZr4yxRIIoBJjsFaqfefe/QE3706RyAfTolQ6o0OlSQhcsNIxlBT4ynUgWg2uarIac011bRbyH3EhHtHmKc8fNzuJr1GjR8oXxCyvdlrFT5XmsoGrgcq+44z4TUie/T1S5QpdJDIyGAaOxPoerzuyIfU+viqtrVlSgCiA25B9sDq6BQCnC7xwZjxea/4sK4FvwQasVn91hxVn1SMi0PH9yR7uf2JqUupuSRsx9Irv9DW+md6WcA3li9+ftM/FAsSLqU4prE/ig1HTYswadjziwBrbtEeimbHgc5cOvCTDzE/KIa99eZaAcaBtBR1ZA2yCIjqJcGxSdQTftG8ND8g23uXoe4C95wju3T7/hJ/Y2irXok6MAVlE31mpPBS1akKWIQnN7hO2ZRBkZAH3GTf3BkCazoPxT0iCGYWID6ZGFX7kJUi7Pj5ZglXLTcj/SB8rvW/73lAsh9dVw1yqOvhl897YVSQcHuTs4hvqt5KDj5MsMyYtsyUNhkz9o/9LoMbRWYIE2cbhW8f/aCNNVCi1cC/ZWogEyafsHuBtg=
  skip_cleanup: true
  on:
    tags: true
    repo: utilitycss/utility
